#!/usr/bin/env python3
"""Zero-AI-trace delivery gate.

Scans every file in a delivery for traces that must never reach a client:
model/vendor names, "generated by AI" footers, filler sign-off phrases,
personal attributions, stray emoji in technical docs, junk files, and the
author field hidden in Office document metadata. Findings are graded
BLOCK / WARN.

This is a deterministic gate, not a prompt: it does not rely on the model
remembering to behave. Run it as a post-task hook and as a standalone scanner
before you hand anything off.

    python3 delivery_lint.py <dir> [--strict] [--json]

The list of personal names to block is configuration, not code — set
POD_BLOCKED_NAMES in your environment. This repo ships no real name.
"""
import os
import re
import sys
import json
import zipfile

try:
    from . import settings
    BLOCKED_NAMES = settings.BLOCKED_NAMES
except Exception:
    BLOCKED_NAMES = [n.strip() for n in os.environ.get("POD_BLOCKED_NAMES", "").split(",") if n.strip()]

TEXT_EXT = {".md", ".markdown", ".txt", ".m", ".py", ".js", ".ts", ".c", ".cpp",
            ".h", ".java", ".html", ".css", ".json", ".csv", ".tsv", ".tex",
            ".mmd", ".mermaid", ".yml", ".yaml", ".sh", ".bat", ".ps1", ".xml"}
OFFICE_EXT = {".docx", ".pptx", ".xlsx"}
JUNK_NAMES = {".ds_store", "thumbs.db", "desktop.ini"}
JUNK_DIRS = {"__pycache__", ".git", "node_modules", ".venv", "venv",
             ".idea", ".vscode", ".pytest_cache", ".mypy_cache"}
JUNK_SUFFIX = (".pyc", ".pyo", ".log", ".tmp", ".bak", ".swp", ".orig", "~",
               ".asv", ".slxc", ".autosave")

# Model / vendor names that must not appear in a deliverable.
MODEL_PATTERNS = [
    r"\bclaude\b", r"\banthropic\b", r"\bchatgpt\b", r"\bgpt-?[0-9]", r"\bopenai\b",
    r"\bcodex\b", r"\bcopilot\b", r"\bgemini\b", r"\bdeepseek\b", r"\bqwen\b",
    r"\bllama\b", r"\bmistral\b", r"\bgrok\b",
]
# "Generated by AI" / robot footers.
GENERATED_PATTERNS = [
    r"generated by", r"co-authored-by", r"\U0001F916", r"as an ai", r"i am an ai",
    r"language model", r"powered by",
]
# Filler / sign-off tails.
CLICHE_PATTERNS = [
    r"\btl;?dr\b", r"in conclusion,", r"i hope this helps", r"feel free to",
    r"let me know if", r"综上所述", r"希望(?:以上|这|对您|对你|能帮)", r"总而言之",
]
# Personal attribution. Generic patterns plus your configured blocked names.
ATTRIBUTION_PATTERNS = [
    r"作者[:：]\s*\S", r"\bauthor\s*[:：]\s*\S", r"署名[:：]",
    r"撰写人[:：]", r"完成人[:：]", r"\bby\s+[A-Z][a-z]+\s+[A-Z][a-z]+",
] + [re.escape(n) for n in BLOCKED_NAMES]

SEVERITY = {"model": "BLOCK", "generated": "BLOCK", "attribution": "BLOCK",
            "cliche": "WARN", "junk": "WARN", "emoji": "WARN", "meta": "BLOCK"}

EMOJI_RE = re.compile(
    "[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F1E6-\U0001F1FF]")


def _compile(pats):
    return [re.compile(p, re.IGNORECASE) for p in pats]


GROUPS = {
    "model": _compile(MODEL_PATTERNS),
    "generated": _compile(GENERATED_PATTERNS),
    "cliche": _compile(CLICHE_PATTERNS),
    "attribution": _compile(ATTRIBUTION_PATTERNS),
}


def scan_text(rel, text, findings):
    for i, line in enumerate(text.splitlines(), 1):
        for group, regexes in GROUPS.items():
            for rx in regexes:
                if not rx.pattern:
                    continue
                m = rx.search(line)
                if m:
                    findings.append((SEVERITY[group], group, rel, i, m.group(0).strip()[:60]))
        if EMOJI_RE.search(line) and rel.rsplit(".", 1)[-1].lower() in {
                "md", "markdown", "txt", "m", "py", "tex", "html"}:
            findings.append((SEVERITY["emoji"], "emoji", rel, i, "emoji in technical doc"))


def scan_office_meta(path, rel, findings):
    """Author fields hidden in docx/pptx/xlsx core.xml."""
    try:
        with zipfile.ZipFile(path) as z:
            if "docProps/core.xml" in z.namelist():
                core = z.read("docProps/core.xml").decode("utf-8", "ignore")
                for tag in ("creator", "lastModifiedBy"):
                    m = (re.search(rf"<dc:{tag}>([^<]+)</dc:{tag}>", core) or
                         re.search(rf"<cp:{tag}>([^<]+)</cp:{tag}>", core))
                    if m and m.group(1).strip():
                        findings.append(("BLOCK", "meta", rel, 0,
                                         f"{tag}={m.group(1).strip()[:40]}"))
    except Exception:
        pass


def run(root):
    findings = []
    for cur, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in JUNK_DIRS]
        for name in files:
            full = os.path.join(cur, name)
            rel = os.path.relpath(full, root).replace("\\", "/")
            low = name.lower()
            ext = os.path.splitext(low)[1]
            if low in JUNK_NAMES or low.endswith(JUNK_SUFFIX):
                findings.append(("WARN", "junk", rel, 0, "junk file"))
                continue
            if ext in TEXT_EXT:
                try:
                    with open(full, "r", encoding="utf-8", errors="ignore") as f:
                        scan_text(rel, f.read(), findings)
                except OSError:
                    pass
            elif ext in OFFICE_EXT:
                scan_office_meta(full, rel, findings)
    return findings


def main():
    if len(sys.argv) < 2:
        print("usage: delivery_lint.py <dir> [--strict] [--json]")
        sys.exit(2)
    root = sys.argv[1]
    as_json = "--json" in sys.argv
    strict = "--strict" in sys.argv
    findings = run(root)
    blocks = [f for f in findings if f[0] == "BLOCK"]
    warns = [f for f in findings if f[0] == "WARN"]
    if as_json:
        print(json.dumps([{"severity": s, "kind": k, "file": p, "line": ln, "match": mt}
                          for s, k, p, ln, mt in findings], ensure_ascii=False, indent=2))
    else:
        if not findings:
            print("PASS: no AI traces / attribution / junk found")
        for s, k, p, ln, mt in sorted(findings, key=lambda x: (x[0] != "BLOCK", x[2])):
            loc = f"{p}:{ln}" if ln else p
            print(f"[{s}] {k:10} {loc}  ->  {mt}")
        print(f"\nsummary: BLOCK={len(blocks)} WARN={len(warns)}")
    sys.exit(1 if blocks or (strict and warns) else 0)


if __name__ == "__main__":
    main()
